"""Default project policy installed by Tessera Harden."""
from __future__ import annotations

from typing import Any

SCHEMA_VERSION = 2

DEFAULT_POLICY: dict[str, Any] = {
    "schema_version": SCHEMA_VERSION,
    "protected_path_globs": [
        ".env",
        ".env.*",
        "**/.env",
        "**/.env.*",
        "**/credentials",
        "**/credentials.*",
        "**/*credential*.json",
        "**/*secret*.json",
        "**/*.pem",
        "**/*.key",
        "**/id_rsa",
        "**/id_ed25519",
        "**/.aws/credentials",
        "**/.ssh/*",
    ],
    "protected_path_exceptions": [
        ".env.example",
        ".env.sample",
        ".env.template",
        "**/.env.example",
        "**/.env.sample",
        "**/.env.template",
    ],
    "governance_path_globs": [
        "CLAUDE.md",
        ".claude/CLAUDE.md",
        ".claude/settings.json",
        ".claude/settings.local.json",
        ".claude/tessera-policy.json",
        ".claude/hooks/**",
        ".claude/rules/**",
        ".mcp.json",
        "policy/**",
        ".tessera/install-manifest.json",
        ".tessera/governance-inventory.json",
        ".tessera/rule-to-hook-map.md",
        ".tessera/verification.json",
        ".tessera/receipts/**",
        ".tessera/backups/**",
    ],
    "production_markers": [
        "production",
        "--prod",
        "--environment prod",
        "--environment=prod",
        "-e prod",
        "namespace/prod",
        "context prod",
    ],
    "test_command_patterns": [
        "pytest",
        "python -m pytest",
        "npm test",
        "npm run test",
        "pnpm test",
        "yarn test",
        "bun test",
        "cargo test",
        "go test",
        "dotnet test",
        "mvn test",
        "gradle test",
        "./gradlew test",
    ],
    "max_test_reminders": 2,
    "receipt_path": ".tessera/receipts/hooks.jsonl",
    "verification_receipt_path": ".tessera/receipts/verification-hooks.jsonl",
    "state_dir": ".tessera/state",
}
